version: "3"

services:
  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - 8080:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - network
    depends_on:
      - login

  mongo:
    image: mongo:5.0.7-focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
    networks:
      - network

  login:
    build:
      context: ./login
    volumes:
      - ./login:/service
    depends_on:
      - mongo
    networks:
      - network

  signup:
    build:
      context: ./signup
    volumes:
      - ./signup:/service
    depends_on:
      - mongo
    networks:
      - network

networks:
  network:
